### ISSUE TITLE
Fix chapter verification

### ISSUE THREAD

**Issue by LE-Oliveira** [CodeWracker/MangaBookmark-Chrome-Extension#9]
If someone adds a title without adding a chapter, it is saved as null, which doesn't allow incremention. Only after decrementing it, the counting starts to work properly (there must already be a verification working here). The most likely solution is to use a verification such as:

If(chapter == NULL){
      chapter = 0;
}

when adding a new manga.

**Comment by CodeWracker** [comment]
Corrigido com o commit 1d37e835c0cdc1938f764d51c0d4d103f8476024, caso ainda persista o bug reabra a issue
